// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk9QZ0cIfpeBP2EJ6aZfTHncmg7opphNQ',
    appId: '1:281981409319:web:b1300598e2454b72819602',
    messagingSenderId: '281981409319',
    projectId: 'anyskill-6fdf3',
    authDomain: 'anyskill-6fdf3.firebaseapp.com',
    storageBucket: 'anyskill-6fdf3.firebasestorage.app',
    measurementId: 'G-03B1X40509',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvNTA5b1pmZbwfbRnpKNM51vKNu-n8YVg',
    appId: '1:281981409319:android:b079b10f298b41d8819602',
    messagingSenderId: '281981409319',
    projectId: 'anyskill-6fdf3',
    storageBucket: 'anyskill-6fdf3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlZJ_m5fW2pSw65xCQApIfVi3JVr-qR4E',
    appId: '1:281981409319:ios:020c7e05b8c1e258819602',
    messagingSenderId: '281981409319',
    projectId: 'anyskill-6fdf3',
    storageBucket: 'anyskill-6fdf3.firebasestorage.app',
    iosBundleId: 'com.example.anyskillApp',
    iosClientId:
        '281981409319-abse2ege4k4uqi0abdlkvhmea56ub2kl.apps.googleusercontent.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlZJ_m5fW2pSw65xCQApIfVi3JVr-qR4E',
    appId: '1:281981409319:ios:020c7e05b8c1e258819602',
    messagingSenderId: '281981409319',
    projectId: 'anyskill-6fdf3',
    storageBucket: 'anyskill-6fdf3.firebasestorage.app',
    iosBundleId: 'com.example.anyskillApp',
    iosClientId:
        '281981409319-abse2ege4k4uqi0abdlkvhmea56ub2kl.apps.googleusercontent.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk9QZ0cIfpeBP2EJ6aZfTHncmg7opphNQ',
    appId: '1:281981409319:web:5b2131bb9985df2c819602',
    messagingSenderId: '281981409319',
    projectId: 'anyskill-6fdf3',
    authDomain: 'anyskill-6fdf3.web.app',
    storageBucket: 'anyskill-6fdf3.firebasestorage.app',
    measurementId: 'G-6P433S6E7G',
  );
}
